# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MianWIndow(object):
    def setupUi(self, MianWIndow):
        MianWIndow.setObjectName("MianWIndow")
        MianWIndow.resize(1007, 708)
        self.widget = QtWidgets.QWidget(MianWIndow)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1001, 71))
        self.widget.setObjectName("widget")
        self.pushButton_request = QtWidgets.QPushButton(self.widget)
        self.pushButton_request.setGeometry(QtCore.QRect(720, 20, 112, 24))
        self.pushButton_request.setObjectName("pushButton_request")
        self.comboBox_way = QtWidgets.QComboBox(self.widget)
        self.comboBox_way.setGeometry(QtCore.QRect(90, 20, 421, 24))
        self.comboBox_way.setEditable(False)
        self.comboBox_way.setCurrentText("")
        self.comboBox_way.setObjectName("comboBox_way")
        self.pushButton_requestall = QtWidgets.QPushButton(self.widget)
        self.pushButton_requestall.setGeometry(QtCore.QRect(860, 20, 112, 24))
        self.pushButton_requestall.setObjectName("pushButton_requestall")
        self.label_method = QtWidgets.QLabel(self.widget)
        self.label_method.setGeometry(QtCore.QRect(580, 20, 81, 24))
        self.label_method.setText("")
        self.label_method.setObjectName("label_method")
        self.pushButton_in = QtWidgets.QPushButton(self.widget)
        self.pushButton_in.setGeometry(QtCore.QRect(20, 20, 48, 24))
        self.pushButton_in.setObjectName("pushButton_in")
        self.checkBox_header = QtWidgets.QCheckBox(MianWIndow)
        self.checkBox_header.setGeometry(QtCore.QRect(20, 90, 81, 22))
        self.checkBox_header.setObjectName("checkBox_header")
        self.checkBox_query = QtWidgets.QCheckBox(MianWIndow)
        self.checkBox_query.setGeometry(QtCore.QRect(110, 90, 81, 22))
        self.checkBox_query.setObjectName("checkBox_query")
        self.widget_param = QtWidgets.QWidget(MianWIndow)
        self.widget_param.setGeometry(QtCore.QRect(10, 130, 991, 201))
        self.widget_param.setObjectName("widget_param")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget_param)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 991, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Layout_param = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Layout_param.setContentsMargins(0, 0, 0, 0)
        self.Layout_param.setObjectName("Layout_param")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Layout_param.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_param.addItem(spacerItem1)
        self.verticalLayoutWidget = QtWidgets.QWidget(MianWIndow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(330, 70, 671, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_path = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.verticalLayout.addWidget(self.lineEdit_path)
        self.widget_body = QtWidgets.QWidget(MianWIndow)
        self.widget_body.setGeometry(QtCore.QRect(210, 70, 111, 61))
        self.widget_body.setObjectName("widget_body")
        self.checkBox_body = QtWidgets.QCheckBox(self.widget_body)
        self.checkBox_body.setGeometry(QtCore.QRect(10, 20, 81, 22))
        self.checkBox_body.setObjectName("checkBox_body")
        self.scrollArea_result = QtWidgets.QScrollArea(MianWIndow)
        self.scrollArea_result.setGeometry(QtCore.QRect(10, 380, 311, 321))
        self.scrollArea_result.setWidgetResizable(True)
        self.scrollArea_result.setObjectName("scrollArea_result")
        self.scrollAreaWidgetContents_result = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_result.setGeometry(QtCore.QRect(0, 0, 309, 319))
        self.scrollAreaWidgetContents_result.setObjectName("scrollAreaWidgetContents_result")
        self.textBrowser_result = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_result)
        self.textBrowser_result.setGeometry(QtCore.QRect(0, 0, 311, 321))
        self.textBrowser_result.setObjectName("textBrowser_result")
        self.scrollArea_result.setWidget(self.scrollAreaWidgetContents_result)
        self.label = QtWidgets.QLabel(MianWIndow)
        self.label.setGeometry(QtCore.QRect(10, 350, 81, 18))
        self.label.setObjectName("label")

        self.retranslateUi(MianWIndow)
        QtCore.QMetaObject.connectSlotsByName(MianWIndow)

    def retranslateUi(self, MianWIndow):
        _translate = QtCore.QCoreApplication.translate
        MianWIndow.setWindowTitle(_translate("MianWIndow", "Form"))
        self.pushButton_request.setText(_translate("MianWIndow", "测试"))
        self.pushButton_requestall.setText(_translate("MianWIndow", "测试所有"))
        self.pushButton_in.setText(_translate("MianWIndow", "导入"))
        self.checkBox_header.setText(_translate("MianWIndow", "Header"))
        self.checkBox_query.setText(_translate("MianWIndow", "Query"))
        self.checkBox_body.setText(_translate("MianWIndow", "Body"))
        self.label.setText(_translate("MianWIndow", "result"))

