# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MianWIndow(object):
    def setupUi(self, MianWIndow):
        MianWIndow.setObjectName("MianWIndow")
        MianWIndow.resize(1007, 708)
        MianWIndow.setMinimumSize(QtCore.QSize(1007, 708))
        MianWIndow.setMaximumSize(QtCore.QSize(1007, 708))
        self.scrollArea = QtWidgets.QScrollArea(MianWIndow)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1011, 711))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1009, 709))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton_clear = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_clear.setGeometry(QtCore.QRect(260, 350, 60, 24))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.widget_param = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_param.setGeometry(QtCore.QRect(10, 130, 991, 201))
        self.widget_param.setObjectName("widget_param")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget_param)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 991, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Layout_param = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Layout_param.setContentsMargins(0, 0, 0, 0)
        self.Layout_param.setObjectName("Layout_param")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Layout_param.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_param.addItem(spacerItem1)
        self.scrollArea_result = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_result.setGeometry(QtCore.QRect(10, 380, 311, 321))
        self.scrollArea_result.setWidgetResizable(True)
        self.scrollArea_result.setObjectName("scrollArea_result")
        self.scrollAreaWidgetContents_result = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_result.setGeometry(QtCore.QRect(0, 0, 309, 319))
        self.scrollAreaWidgetContents_result.setObjectName("scrollAreaWidgetContents_result")
        self.textBrowser_result = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_result)
        self.textBrowser_result.setGeometry(QtCore.QRect(0, 0, 311, 321))
        self.textBrowser_result.setObjectName("textBrowser_result")
        self.scrollArea_result.setWidget(self.scrollAreaWidgetContents_result)
        self.widget_body = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_body.setGeometry(QtCore.QRect(210, 70, 111, 61))
        self.widget_body.setObjectName("widget_body")
        self.checkBox_body = QtWidgets.QCheckBox(self.widget_body)
        self.checkBox_body.setGeometry(QtCore.QRect(10, 20, 81, 22))
        self.checkBox_body.setObjectName("checkBox_body")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(330, 70, 571, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_path = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.verticalLayout.addWidget(self.lineEdit_path)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(10, 350, 71, 24))
        self.label.setStyleSheet("\n"
"font: 87 9pt \"Arial\";")
        self.label.setObjectName("label")
        self.checkBox_header = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_header.setGeometry(QtCore.QRect(20, 90, 81, 22))
        self.checkBox_header.setObjectName("checkBox_header")
        self.checkBox_query = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_query.setGeometry(QtCore.QRect(110, 90, 81, 22))
        self.checkBox_query.setObjectName("checkBox_query")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1001, 71))
        self.widget.setObjectName("widget")
        self.pushButton_request = QtWidgets.QPushButton(self.widget)
        self.pushButton_request.setGeometry(QtCore.QRect(720, 20, 112, 24))
        self.pushButton_request.setObjectName("pushButton_request")
        self.comboBox_way = QtWidgets.QComboBox(self.widget)
        self.comboBox_way.setGeometry(QtCore.QRect(90, 20, 421, 24))
        self.comboBox_way.setEditable(False)
        self.comboBox_way.setCurrentText("")
        self.comboBox_way.setObjectName("comboBox_way")
        self.pushButton_requestall = QtWidgets.QPushButton(self.widget)
        self.pushButton_requestall.setGeometry(QtCore.QRect(860, 20, 112, 24))
        self.pushButton_requestall.setObjectName("pushButton_requestall")
        self.label_method = QtWidgets.QLabel(self.widget)
        self.label_method.setGeometry(QtCore.QRect(580, 20, 81, 24))
        self.label_method.setText("")
        self.label_method.setObjectName("label_method")
        self.pushButton_in = QtWidgets.QPushButton(self.widget)
        self.pushButton_in.setGeometry(QtCore.QRect(20, 20, 48, 24))
        self.pushButton_in.setObjectName("pushButton_in")
        self.label_requeststatus = QtWidgets.QLabel(self.widget)
        self.label_requeststatus.setGeometry(QtCore.QRect(722, 49, 261, 18))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_requeststatus.setFont(font)
        self.label_requeststatus.setStyleSheet("")
        self.label_requeststatus.setText("")
        self.label_requeststatus.setObjectName("label_requeststatus")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setGeometry(QtCore.QRect(340, 380, 661, 321))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 659, 319))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.textBrowser_responsebody = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.textBrowser_responsebody.setGeometry(QtCore.QRect(0, 0, 661, 321))
        self.textBrowser_responsebody.setObjectName("textBrowser_responsebody")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(340, 350, 131, 18))
        self.label_2.setStyleSheet("font: 87 9pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_save = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_save.setGeometry(QtCore.QRect(920, 88, 50, 25))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_saveAll = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_saveAll.setGeometry(QtCore.QRect(851, 340, 151, 24))
        self.pushButton_saveAll.setObjectName("pushButton_saveAll")
        self.pushButton_export = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_export.setGeometry(QtCore.QRect(130, 350, 60, 24))
        self.pushButton_export.setObjectName("pushButton_export")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(MianWIndow)
        QtCore.QMetaObject.connectSlotsByName(MianWIndow)

    def retranslateUi(self, MianWIndow):
        _translate = QtCore.QCoreApplication.translate
        MianWIndow.setWindowTitle(_translate("MianWIndow", "Form"))
        self.pushButton_clear.setText(_translate("MianWIndow", "clear"))
        self.checkBox_body.setText(_translate("MianWIndow", "Body"))
        self.label.setText(_translate("MianWIndow", "Status"))
        self.checkBox_header.setText(_translate("MianWIndow", "Header"))
        self.checkBox_query.setText(_translate("MianWIndow", "Query"))
        self.pushButton_request.setText(_translate("MianWIndow", "测试"))
        self.pushButton_requestall.setText(_translate("MianWIndow", "测试所有"))
        self.pushButton_in.setText(_translate("MianWIndow", "导入"))
        self.label_2.setText(_translate("MianWIndow", "ResponseBody"))
        self.pushButton_save.setText(_translate("MianWIndow", "保存"))
        self.pushButton_saveAll.setText(_translate("MianWIndow", "▲保存所有修改"))
        self.pushButton_export.setText(_translate("MianWIndow", "export"))

